[package]
name = "gridpx"
version = "0.1.0"
edition = "2021"
description = "A lightweight, stack-allocated, fixed-size 2D grid structure for Rust, built with const generics for zero-heap allocation overhead."
license = "MIT OR Apache-2.0"
repository = "https://github.com/nanashi-1/gridpx"
documentation = "https://docs.rs/gridpx"
homepage = "https://github.com/nanashi-1/gridpx"

[dependencies]
thiserror = "2.0.18"

[workspace]
members = ["examples/conways-game-of-life","examples/tic-tac-toe"]
